### ISSUE TITLE
V3: error with clones in useGet

### ISSUE THREAD

**Issue by ericuldall** [marshallswain/feathers-pinia#121]
```
    Uncaught (in promise) TypeError: Cannot read properties of null (reading 'clone')
    at ReactiveEffect.fn (local-queries.ts:150:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at get value [as value] (reactivity.esm-bundler.js:1171:39)
    at ReactiveEffect.fn (use-get.ts:41:63)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at get value [as value] (reactivity.esm-bundler.js:1171:39)
```
Here's my implementation:
```
(async () => {
        const { data, get } = Users.useGet(id, { clones: true });
        await get();
        data.value.name = 'updated name';
        data.value.save();
})();
```

**Comment by ericuldall** [comment]
PEBCAK. id was pulled via user._id, needed to user user.value._id;
